### ISSUE TITLE
Tiny program icons with 4K resolution

### ISSUE THREAD

**Issue by beaumanvienna** [rcasero/doc#2]
Hi, I hope it's Okay if I ask a question here because no one did before me.

I've got a brand new DELL XPS 15 9550 on which I today installed Ubuntu 16.4. The machine runs really nice, but I haven't managed to configure the desktop properly for a 4k resolution.  The problem is that some programs have tiny icons if I crank the resolution all the way up.  Not all though, because I did find this scaling slider for menus and bars in the system settings under 'Displays', which allows me to configure the interface of most programs with a decent size. It works well for the log-on screen, the taskbar, and the desktop programs, but other applications such as VLC and Gimp would still have these teeny controls. 

Please refer to the attached screenshot. Any suggestions?

Thanks!

Regards,
JC

**Comment by rcasero** [comment]
Hi, @beaumanvienna . I think this type of question makes more sense in the [ubuntu forums, desktop environments](https://ubuntuforums.org/forumdisplay.php?f=329).
