### ISSUE TITLE
Touchpad troubleshooting question for 16.04 on XPS 15

### ISSUE THREAD

**Issue by arkhipenko** [rcasero/doc#21]
Hi,

First of all, thank you for the ubuntu install guide for XPS 15 - saved me countless hours I am sure, and also confirmed that ubuntu is possible on Dell XPS!

When I try to run the Touchpad troubleshooting step from this link:
https://github.com/rcasero/doc/wiki/Ubuntu-linux-on-Dell-XPS-15-(9560)#touchpad

this specific one:
`sudo apt-get install xserver-xorg-input-libinput`

apt suggest removing a lot of packages. And I am concerned it will wreck the system.

```
anatoli@xps:~$ sudo apt-get install xserver-xorg-input-libinput
[sudo] password for anatoli: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-libinput : Depends: xorg-input-abi-22
                               Depends: xserver-xorg-core (>= 2:1.17.99.902)
E: Unable to correct problems, you have held broken packages.

anatoli@xps:~$ sudo apt-get install xorg-input-abi-22
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'xserver-xorg-core' instead of 'xorg-input-abi-22'
The following packages were automatically installed and are no longer required:
  libxfont2 xserver-xorg-legacy-hwe-16.04
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  xfonts-100dpi | xfonts-75dpi
The following packages will be REMOVED:
  xorg xserver-xorg-core-hwe-16.04 xserver-xorg-hwe-16.04 xserver-xorg-input-all-hwe-16.04
  xserver-xorg-input-evdev-hwe-16.04 xserver-xorg-input-synaptics-hwe-16.04 xserver-xorg-input-wacom-hwe-16.04
  xserver-xorg-video-all-hwe-16.04 xserver-xorg-video-amdgpu-hwe-16.04 xserver-xorg-video-ati-hwe-16.04
  xserver-xorg-video-fbdev-hwe-16.04 xserver-xorg-video-intel-hwe-16.04 xserver-xorg-video-nouveau-hwe-16.04
  xserver-xorg-video-qxl-hwe-16.04 xserver-xorg-video-radeon-hwe-16.04 xserver-xorg-video-vesa-hwe-16.04
  xserver-xorg-video-vmware-hwe-16.04 xubuntu-core xubuntu-desktop
The following NEW packages will be installed:
  xserver-xorg-core
0 upgraded, 1 newly installed, 19 to remove and 0 not upgraded.
Need to get 1,344 kB of archives.
After this operation, 5,692 kB disk space will be freed.
Do you want to continue? [Y/n] n
```

I am running Xubuntu 16.04
`Linux xps 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
Would you be able to recommend if I should go ahead or not?

Thanks in advance.

**Comment by rcasero** [comment]
Hi @arkhipenko ,

If you remove those packages, yes, you'll break your system. The guide is for Ubuntu, so if you want to install Xubuntu, the packages you need may be different.

Do you actually get the problem with the touchpad? Maybe in your system, that's not a problem. If it is, check with `apt-cache search libinput xserver` to look for the package that suits your distribution.

In any case, just to point out that 16.04 is a bit outdated now, and won't get hardware updates anymore according to the [release end of life](https://www.ubuntu.com/info/release-end-of-life). 18.04 is the new LTS.

@Peter-Strain has managed to install it, with [these fixes](https://github.com/rcasero/doc/issues/20). I'll write a guide soon.

**Comment by arkhipenko** [comment]
Thank you - this is very helpful.  I realize 16.04 is outdated but I did not want to fight with a new install - your guide sort of guarantees 16.04 will install and run. I might try 18.04 upgrade after doing a full backup :)
