### ISSUE TITLE
4K Resolution Issues

### ISSUE THREAD

**Issue by Igor-Gold** [rcasero/doc#22]
I've been pulling my hair for the past two days trying to figure out why my 4k screen on my XPS would not scale properly on Ubuntu.

Finally found [this](https://askubuntu.com/questions/978663/xrandr-failed-to-get-size-of-gamma-for-output-default-for-mdp-type-connection) article.

I know the 9560 isn't coffeelake, but I'm pretty sure a lot of people with 9570s are going to be using your wiki.

I think making it a bit more generic would be a good idea.

The solution for the resolution problem for coffeelake systems:

Add this to grub boot loader options: `i915.alpha_support=1`

Source: [Coffee Lake on Linux](https://www.phoronix.com/scan.php?page=article&item=coffee-uhd-graphics&num=1)

**Comment by rcasero** [comment]
Hi @IgorGee , 

Thanks for the heads up. What do you mean exactly by "my 4k screen on my XPS would not scale properly on Ubuntu"? Can you explain the problem in some more detail, what version of Ubuntu you are using, etc?

**Comment by Igor-Gold** [comment]
I don't know how to use the proper terminology, but when I say "not scale properly", all icons, font, windows, etc will be incredibly small from the user's perspective.

What operating systems normally do in the situation is magnify these elements by some factor. On a 4k monitor, usually by a factor of ~2.

You can read more about it [here](https://pcmonitors.info/articles/the-4k-uhd-3840-x-2160-experience/#The_desktop_experience) (uses windows as example but same applies to any OS).

Ubuntu Version: `16.04.4`

**Comment by rcasero** [comment]
Thanks for the clarification. 

Sorry to be pedantic ;), but 9560 is a Dell laptop model, and Coffee Lake is an Intel name for a round of chips. So saying "the 9560 isn't coffeelake" is a bit confusing, as these are two different things.

So you have one of the new Dell XPS 9570, that ships with a Coffe Lake chip, and when you plug an external 4K monitor running Ubuntu 16.04.4, the fonts/icons/windows look too small, right?

You have found as a solution enabling the "alpha" quality driver support in Linux 4.13~4.14 for Coffee Lake adding to grub

```
i915.alpha_support=1
```

as suggested by M. Larabel in ["Intel UHD Graphics 630 "Coffee Lake" On Linux"](https://www.phoronix.com/scan.php?page=article&item=coffee-uhd-graphics&num=1). Thanks, that'll be very useful for people with new laptops.

For convenience, I'm copy&pasting here [the steps by marekbrze](https://askubuntu.com/questions/978663/xrandr-failed-to-get-size-of-gamma-for-output-default-for-mdp-type-connection) that you link to

1. Log in to the system and start a terminal window (Applications->Accessories->Terminal).

1. In the terminal window at the $ prompt, enter the command: `sudo gedit /etc/default/grub`.

1. Enter your password when prompted by `sudo`. (If the file `/etc/default/grub` appears to be empty or does not exist, see the instructions for earlier releases above).

1. In the editor window, use the arrow keys to move the cursor to the line beginning with`GRUB_CMDLINE_LINUX_DEFAULT` then edit that line, adding your parameter(s) to the text inside the double-quotes after the words `quiet splash`. (Be sure to add a SPACE after `splash` before adding your new parameter).

1. it should look like this `quiet splash i915.alpha_support=1`.

1. Click the Save button, then close the editor window.

1. In the terminal window at the `$` prompt, enter the command: `sudo update-grub`.

1. Restart the system.

Now your 16.04.4 is quite old, but Larabel mentions the problem even for Ubuntu 17.10. There's a new LTS in Ubuntu, 18.04 Bionic Beaver (which I haven't upgraded to yet, by the way). Have you tried that version by any chance? It provides Linux kernel 4.15, whereas Larabel found the problem for 4.13~4.14.

**Comment by Igor-Gold** [comment]
I haven't gone beyond 16.04 and don't intend to for the time being.

My 4k issue was with the 4k monitor on my XPS, not an external monitor.

**Comment by rcasero** [comment]
Ah, OK, as you said, it was your 4K screen. Sorry, I misunderstood that bit.
