### ISSUE TITLE
nouveau issue during ubuntu 16.04.03 install

### ISSUE THREAD

**Issue by mantonovic** [rcasero/doc#6]
Hi @rcasero,
Thanks for your tutorial it was very useful to install Ubuntu 16.04.03 on my Dell XPS 15 9560 (BIOS version 1.5.0).

I had only one issue, during installation from the USB (try before install), Ubuntu did not started.. There were some error messages related to the nouveau driver.

Finally I found a solution [1] that permitted me to boot correctly. I had to add the following boot parameter at startup:

`nouveau.modeset=0`

then everything worked as expected..

And, not sure if mandatory, but I also added as boot param:

`nvme_load=YES`

[1] https://rileymacdonald.ca/2017/06/26/ubuntu-broken-boot-on-dell-xps-15-after-kernel-update-upgrade/

**Comment by kiran072** [comment]
Hi @mantonovic  How did you add the following boot parameter:
nouveau.modeset=0

Thanks
Kiran Asknani

**Comment by mantonovic** [comment]
During installation when Ubuntu is starting from USB [1] add the boot parameters.

[1] Take a look at "Changing the CD's Default Boot Options": https://help.ubuntu.com/community/BootOptions

**Comment by mantonovic** [comment]
@kiran072 then after installation you can test others config parameters on boot [1]. And when everything is OK modify the grub file as explained in the guide.

[1] https://wiki.ubuntu.com/Kernel/KernelBootParameters

**Comment by daxmc99** [comment]
I had an issue with Ubuntu Install from Live USB hanging and followed [Dell's](http://www.dell.com/support/article/us/en/19/sln306327/manual--nomodeset--kernal-boot-line-option-for-linux-booting?lang=en) solution of adding nomodeset to the boot options.

**Comment by rcasero** [comment]
@mantonovic Sorry for the slow reply. This was an excellent contribution, thanks. I've added it to the wiki.

I found the same problem booting Ubuntu Live 17.10. Just adding`nouveau.modeset=0` to the boot options, as you suggests, solves the problem.

https://github.com/rcasero/doc/wiki/Ubuntu-linux-on-Dell-XPS-15-(9560)#installing-ubuntu

**Comment by vilis198** [comment]
I plugged the USB into the port on the right side. Boots perfectly.
While plugging into the left side USB, Ubuntu doesn't start - hangs up during startup.

**Comment by smtheard** [comment]
nomodeset did not work for me, it still froze. Switching to the other USB port also did not work for me either, still froze. The solution for me was to add the acpi=off boot option.. Very odd problem, posting here in case anyone hits the same issue.

**Comment by bradt** [comment]
> I had an issue with Ubuntu Install from Live USB hanging and followed Dell's solution of adding nomodeset to the boot options.

This is what worked for me with 18.04 LTS
